name: Build Dist and Rlease
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          cache-dependency-path: ./package.json
          cache: 'npm'
      - run: npm install
      - run: npx vite build
      - run: zip -r dist.zip ./dist
      - name: Calculate tag name
        run: |
          name=dev
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            name=${GITHUB_REF:10}
          fi
          echo TAG=$name >> $GITHUB_ENV
        id: tagname
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tagname: ${{ steps.tagname.outputs.val }}
          files: dist.zip